export const RETRIEVE_HISTORY_SUCCESS = 'RETRIEVE_HISTORY_SUCCESS';
export const CREATE_KEYS_SUCCESS      = 'CREATE_KEYS_SUCCESS';
export const MEMO_SUCCESS             = 'MEMO_SUCCESS';
export const RETRIEVE_BALANCE_SUCCESS = 'RETRIEVE_BALANCE_SUCCESS';