// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from bts2helper.djinni

package com.diventi.bts2helper;

import java.util.ArrayList;
import java.util.concurrent.atomic.AtomicBoolean;

/** This interface will be implemented in C++ and can be called from any language. */
public abstract class Bts2helper {
    public static native String txDigest(String txJson, String chainId);

    public static native String signCompact(String digest, String wif);

    public static native boolean isValidName(String name);

    public static native boolean isCheapName(String name);

    public static native ArrayList<Long> calcFee(String feeSchedule, ArrayList<String> ops, String coreExchangeRatio);

    private static final class CppProxy extends Bts2helper
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }
    }
}
