// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from bts2helper.djinni

#import <Foundation/Foundation.h>


/** This interface will be implemented in C++ and can be called from any language. */
@interface B2HBts2helper : NSObject

+ (nonnull NSString *)txDigest:(nonnull NSString *)txJson
                       chainId:(nonnull NSString *)chainId;

+ (nonnull NSString *)signCompact:(nonnull NSString *)digest
                              wif:(nonnull NSString *)wif;

+ (BOOL)isValidName:(nonnull NSString *)name;

+ (BOOL)isCheapName:(nonnull NSString *)name;

+ (nonnull NSArray<NSNumber *> *)calcFee:(nonnull NSString *)feeSchedule
                                     ops:(nonnull NSArray<NSString *> *)ops
                       coreExchangeRatio:(nonnull NSString *)coreExchangeRatio;

+ (nonnull NSString *)encodeMemo:(nonnull NSString *)priv
                             pub:(nonnull NSString *)pub
                             msg:(nonnull NSString *)msg;

+ (nonnull NSString *)decodeMemo:(nonnull NSString *)priv
                             pub:(nonnull NSString *)pub
                        memoFrom:(nonnull NSString *)memoFrom
                          memoTo:(nonnull NSString *)memoTo
                       memoNonce:(nonnull NSString *)memoNonce
                     memoMessage:(nonnull NSString *)memoMessage;

@end
